// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdsgtbdqgtwnywvkquhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indkc2d0YmRxZ3R3bnl3dmtxdWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4MjgyMjEsImV4cCI6MjA4OTQwNDIyMX0.jDOtnSauyl-r6WS-XUJm-uQD0-8Tw31l_IovsO2Lfps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});